---
author: "Bernat Bramon"
date: "7/11/2023"
format: 
  html:
    code-fold: true
---

```{r}
#| echo: false
#| output: false

correlation <- readRDS("./data/processed/correlation.rds")
```


## Nicolas Cage, [`r toString(ifelse(correlation>0.5, "lock him up!", "more please!"))`]{style="color:#F4BA02;"}

@fig-cage explores the relationship between the number of people drowned in pools in the US and the number of movies Nicolas Cage makes a year.

```{r}
#| label: fig-cage
#| fig-cap: Not a suspicious figure 
#| warning: false

library(ggplot2)
library(dplyr)
source("./code/utility.R")

data <- readRDS("./data/processed/data.rds")

dColor <- "#69b3a2"
fColor <- "#bf812d"
coef <- 40

p <- data %>% ggplot(aes(x=year)) +
  geom_line( aes(y=deaths), size=1.5, color=dColor) +
  geom_line( aes(y=films*10 + 80), size=1.5, color=fColor) +
  scale_y_continuous(name = "Swimming pool drownings", limits = c(80, 140),
                     sec.axis = dup_axis(name="Nicolas Cage films", breaks = c(80, 100, 120, 140), labels = c(0,2,4,6))
  ) +
  ggtitle(label = "Drowned by falling into a pool vs Nicolas Cage movies", subtitle = paste0("Presents a correlation of: ", round(correlation, 2))) +
  theme_bw() +
  theme(
    text = element_text(size = 12),
    axis.title.y = element_text(color = dColor, size=12),
    axis.text.y = element_text(color = dColor),
    axis.title.y.right = element_text(color = fColor, size=12),
    axis.text.y.right = element_text(color = fColor),
  )

make_time(4, "Generate figures")

p
```
